name: swiftpark_admin_panel
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  clipboard: ^0.1.3
  cloud_firestore: ^5.4.4
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.6
  data_table_2: ^2.5.15
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_dropzone: ^4.0.3
  flutter_native_splash: ^2.4.1
  flutter_typeahead: ^5.2.0
  get: ^4.6.6
  get_storage: ^2.1.1
  html: ^0.15.4
  http: ^1.2.2
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.2
  multi_select_flutter: ^4.1.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1
  url_strategy: ^0.3.0
  web: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#-----------------------Local Assets-----------------------
#-----------------------Fonts-----------------------
