// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMQUAT4AQst1LochNk2kr5KrContqf-xs',
    appId: '1:443687848456:web:6498f46bf3e406c96f5fbd',
    messagingSenderId: '443687848456',
    projectId: 'swiftpark-8ad2f',
    authDomain: 'swiftpark-8ad2f.firebaseapp.com',
    storageBucket: 'swiftpark-8ad2f.appspot.com',
    measurementId: 'G-5NGF2ZPBTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsBCildLkpv6WNI4zY3JMDKN6z-RX_ce4',
    appId: '1:443687848456:android:a52b9c8152b7ee666f5fbd',
    messagingSenderId: '443687848456',
    projectId: 'swiftpark-8ad2f',
    storageBucket: 'swiftpark-8ad2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAokdLrKFYT9hCz1k_iePFmwYAGZ1_AtYk',
    appId: '1:443687848456:ios:27367d96803234d26f5fbd',
    messagingSenderId: '443687848456',
    projectId: 'swiftpark-8ad2f',
    storageBucket: 'swiftpark-8ad2f.appspot.com',
    androidClientId: '443687848456-monb6do89sdh297p17qmjq9gcjaugj73.apps.googleusercontent.com',
    iosClientId: '443687848456-oacv3f9brbc60v4d2db63mqe06btudi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftparkAdminPanel',
  );
}
